"use client";
import Link from "next/link";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";
type Relic={id:string;file_path:string;title:string|null;author:string|null;source:string|null;url:string|null;notes:string|null;created_at:string};type FormState={title:string;author:string;source:string;url:string;notes:string};const emptyForm:FormState={title:"",author:"",source:"",url:"",notes:""};
export default function RelicPage(){
 const{id}=useParams<{id:string}>();const router=useRouter();const[session,setSession]=useState<Session|null>(null),[relic,setRelic]=useState<Relic|null>(null),[form,setForm]=useState<FormState>(emptyForm),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(false),[editing,setEditing]=useState(false),[message,setMessage]=useState(""),[olderId,setOlderId]=useState<string|null>(null),[newerId,setNewerId]=useState<string|null>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);useEffect(()=>{if(id)void loadRelic()},[id]);
 useEffect(()=>{function key(e:KeyboardEvent){if(e.key==="Escape"){if(editing){setEditing(false);if(relic)setForm({title:relic.title??"",author:relic.author??"",source:relic.source??"",url:relic.url??"",notes:relic.notes??""})}else router.push("/")}else if(!editing&&e.key==="ArrowLeft"&&newerId)router.push(`/relic/${newerId}`);else if(!editing&&e.key==="ArrowRight"&&olderId)router.push(`/relic/${olderId}`)}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[editing,relic,newerId,olderId,router]);
 async function loadRelic(){setLoading(true);setMessage("");const[{data,error},{data:order}]=await Promise.all([supabase.from("images").select("id,file_path,title,author,source,url,notes,created_at").eq("id",id).single(),supabase.from("images").select("id,created_at").order("created_at",{ascending:false}).order("id",{ascending:false})]);if(error){setRelic(null);setMessage(error.message)}else{setRelic(data);setForm({title:data.title??"",author:data.author??"",source:data.source??"",url:data.url??"",notes:data.notes??""})}const index=order?.findIndex(item=>item.id===id)??-1;setNewerId(index>0&&order?order[index-1].id:null);setOlderId(index>=0&&order&&index<order.length-1?order[index+1].id:null);setLoading(false)}
 async function handleSave(e:FormEvent){e.preventDefault();if(!session||!relic)return;setSaving(true);const payload={title:form.title.trim()||null,author:form.author.trim()||null,source:form.source.trim()||null,url:form.url.trim()||null,notes:form.notes.trim()||null};const{error}=await supabase.from("images").update(payload).eq("id",relic.id);if(error)setMessage(error.message);else{setRelic({...relic,...payload});setEditing(false);setMessage("")}setSaving(false)}
 async function handleDelete(){if(!session||!relic||deleting)return;if(!window.confirm("Delete this relic permanently? This cannot be undone."))return;setDeleting(true);setMessage("");const{error:storageError}=await supabase.storage.from("images").remove([relic.file_path]);if(storageError){setMessage(storageError.message);setDeleting(false);return}const{error:dbError}=await supabase.from("images").delete().eq("id",relic.id);if(dbError){setMessage(`Image file was deleted, but database cleanup failed: ${dbError.message}`);setDeleting(false);return}router.push("/")}
 const imageUrl=useMemo(()=>relic?supabase.storage.from("images").getPublicUrl(relic.file_path).data.publicUrl:"",[relic]);
 if(loading)return <main className="min-h-screen bg-white p-4 text-xs text-black/30">Loading...</main>;if(!relic)return <main className="min-h-screen bg-white p-4"><Link href="/" className="text-xs text-black/40">← Back</Link><p className="mt-8 text-sm text-black/50">Relic not found.</p></main>;
 return <main className="min-h-screen bg-white text-black"><header className="flex h-14 items-center justify-between border-b border-black/10 px-4 md:h-16 md:px-6"><Link href="/" className="text-xs text-black/40">← Back</Link><Link href="/" className="text-sm font-bold">eye relics</Link><div className="flex w-28 justify-end gap-4">{session&&!editing&&<><button onClick={()=>setEditing(true)} className="text-[10px] uppercase tracking-[0.18em] text-black/40">Edit</button><button onClick={handleDelete} disabled={deleting} className="text-[10px] uppercase tracking-[0.18em] text-black/25 hover:text-black">{deleting?"Deleting":"Delete"}</button></>}</div></header>
 <div className="mx-auto grid max-w-[1500px] gap-3 px-3 py-3 md:px-6 md:py-6 lg:grid-cols-[minmax(0,1fr)_320px] lg:items-start lg:gap-7 lg:px-10 lg:py-8"><section className="flex items-start justify-center bg-zinc-50">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={imageUrl} alt={relic.title||"Eye Relic"} className="h-auto max-h-[calc(100vh-7rem)] max-w-full object-contain"/></section>
 <aside className="px-1 pb-8">{editing?<form onSubmit={handleSave} className="space-y-3"><Field label="Title" value={form.title} onChange={v=>setForm({...form,title:v})}/><Field label="Author" value={form.author} onChange={v=>setForm({...form,author:v})}/><Field label="Source" value={form.source} onChange={v=>setForm({...form,source:v})}/><Field label="URL" value={form.url} onChange={v=>setForm({...form,url:v})} type="url"/><label className="block"><span className="mb-1 block text-[9px] uppercase tracking-[0.18em] text-black/35">Note</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={5} className="w-full resize-y border border-black/15 bg-transparent p-2 text-sm leading-5 outline-none focus:border-black"/></label><div className="flex gap-5 pt-1"><button disabled={saving} className="text-[10px] font-medium uppercase tracking-[0.18em]">{saving?"Saving":"Save"}</button><button type="button" onClick={()=>setEditing(false)} className="text-[10px] uppercase tracking-[0.18em] text-black/35">Cancel</button></div></form>:<div className="space-y-5"><div><h1 className="text-[26px] font-medium leading-[1.15]">{relic.title||"Untitled"}</h1>{relic.author&&<p className="mt-2 text-sm text-black/55">{relic.author}</p>}</div>{(relic.source||relic.url)&&<div className="space-y-2 text-sm">{relic.source&&<div><p className="mb-1 text-[10px] uppercase tracking-[0.18em] text-black/30">Source</p><p>{relic.source}</p></div>}{relic.url&&<a href={relic.url} target="_blank" rel="noreferrer" className="inline-block text-xs underline decoration-black/20 underline-offset-4">Open original ↗</a>}</div>}{relic.notes&&<div><p className="mb-2 text-[10px] uppercase tracking-[0.18em] text-black/30">Note</p><p className="whitespace-pre-wrap text-sm leading-6 text-black/75">{relic.notes}</p></div>}{!relic.title&&!relic.author&&!relic.source&&!relic.url&&!relic.notes&&<p className="text-xs text-black/30">No information yet.</p>}<div className="flex items-center justify-between border-t border-black/10 pt-4 text-[10px] text-black/35"><span>{newerId?<Link href={`/relic/${newerId}`} className="hover:text-black">← newer</Link>:null}</span><span>{olderId?<Link href={`/relic/${olderId}`} className="hover:text-black">older →</Link>:null}</span></div></div>}{message&&<p className="mt-5 text-xs text-black/45">{message}</p>}</aside></div></main>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block"><span className="mb-1 block text-[9px] uppercase tracking-[0.18em] text-black/35">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full border-b border-black/15 bg-transparent py-1.5 text-sm outline-none focus:border-black"/></label>}
