"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";
type Relic={id:string;file_path:string;title:string|null;author:string|null;source:string|null;url:string|null;notes:string|null;created_at:string};
type FormState={title:string;author:string;source:string;url:string;notes:string};
const emptyForm:FormState={title:"",author:"",source:"",url:"",notes:""};
export default function RelicPage(){
 const params=useParams<{id:string}>();const id=params.id;const[session,setSession]=useState<Session|null>(null);const[relic,setRelic]=useState<Relic|null>(null);const[form,setForm]=useState<FormState>(emptyForm);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[editing,setEditing]=useState(false);const[message,setMessage]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:listener}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>listener.subscription.unsubscribe()},[]);
 useEffect(()=>{if(id)loadRelic()},[id]);
 async function loadRelic(){setLoading(true);setMessage("");const{data,error}=await supabase.from("images").select("id,file_path,title,author,source,url,notes,created_at").eq("id",id).single();if(error){setMessage(error.message);setRelic(null)}else{setRelic(data);setForm({title:data.title??"",author:data.author??"",source:data.source??"",url:data.url??"",notes:data.notes??""})}setLoading(false)}
 async function handleSave(event:FormEvent){event.preventDefault();if(!session||!relic)return;setSaving(true);setMessage("");const payload={title:form.title.trim()||null,author:form.author.trim()||null,source:form.source.trim()||null,url:form.url.trim()||null,notes:form.notes.trim()||null};const{error}=await supabase.from("images").update(payload).eq("id",relic.id);if(error)setMessage(error.message);else{setRelic({...relic,...payload});setEditing(false)}setSaving(false)}
 const imageUrl=useMemo(()=>relic?supabase.storage.from("images").getPublicUrl(relic.file_path).data.publicUrl:"",[relic]);
 if(loading)return <main className="min-h-screen bg-white p-4 text-xs text-black/30">Loading...</main>;
 if(!relic)return <main className="min-h-screen bg-white p-4 text-black"><Link href="/" className="text-xs uppercase tracking-[0.18em] text-black/40">← Back</Link><p className="mt-8 text-sm text-black/50">Relic not found.</p>{message&&<p className="mt-3 text-xs text-black/35">{message}</p>}</main>;
 return <main className="min-h-screen bg-white text-black">
  <header className="flex h-14 items-center justify-between border-b border-black/10 px-4 md:h-16 md:px-6"><Link href="/" className="text-xs uppercase tracking-[0.18em] text-black/40 hover:text-black">← Back</Link><Link href="/" className="text-xs font-semibold tracking-[0.18em] md:text-sm">EYE RELICS</Link><div className="w-16 text-right md:w-20">{session&&!editing&&<button onClick={()=>setEditing(true)} className="text-[10px] uppercase tracking-[0.18em] text-black/40 hover:text-black">Edit</button>}</div></header>
  <div className="mx-auto grid max-w-[1500px] gap-4 px-3 py-3 md:px-6 md:py-6 lg:grid-cols-[minmax(0,1fr)_320px] lg:items-start lg:gap-8 lg:px-10 lg:py-8">
   <section className="flex items-start justify-center bg-zinc-50">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={imageUrl} alt={relic.title||"Eye Relic"} className="h-auto max-h-[calc(100vh-7rem)] max-w-full object-contain"/></section>
   <aside className="px-1 pb-8 md:px-0 lg:pt-0">{editing?<form onSubmit={handleSave} className="space-y-5"><Field label="Title" value={form.title} onChange={v=>setForm({...form,title:v})}/><Field label="Author" value={form.author} onChange={v=>setForm({...form,author:v})}/><Field label="Source" value={form.source} onChange={v=>setForm({...form,source:v})}/><Field label="URL" value={form.url} onChange={v=>setForm({...form,url:v})} type="url"/><label className="block"><span className="mb-2 block text-[10px] uppercase tracking-[0.18em] text-black/35">Note</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={7} className="w-full resize-y border border-black/15 bg-transparent p-3 text-sm leading-6 outline-none focus:border-black"/></label><div className="flex gap-5 pt-1"><button type="submit" disabled={saving} className="text-[10px] font-medium uppercase tracking-[0.18em] disabled:opacity-30">{saving?"Saving":"Save"}</button><button type="button" onClick={()=>{setForm({title:relic.title??"",author:relic.author??"",source:relic.source??"",url:relic.url??"",notes:relic.notes??""});setEditing(false);setMessage("")}} className="text-[10px] uppercase tracking-[0.18em] text-black/35">Cancel</button></div></form>:<div className="space-y-5"><div><h1 className="text-lg font-medium leading-7">{relic.title||"Untitled"}</h1>{relic.author&&<p className="mt-1 text-sm text-black/55">{relic.author}</p>}</div>{(relic.source||relic.url)&&<div className="space-y-2 text-sm">{relic.source&&<div><p className="mb-1 text-[10px] uppercase tracking-[0.18em] text-black/30">Source</p><p>{relic.source}</p></div>}{relic.url&&<a href={relic.url} target="_blank" rel="noreferrer" className="inline-block text-xs underline decoration-black/20 underline-offset-4">Open original ↗</a>}</div>}{relic.notes&&<div><p className="mb-2 text-[10px] uppercase tracking-[0.18em] text-black/30">Note</p><p className="whitespace-pre-wrap text-sm leading-6 text-black/75">{relic.notes}</p></div>}{!relic.title&&!relic.author&&!relic.source&&!relic.url&&!relic.notes&&<p className="text-xs text-black/30">No information yet.</p>}</div>}{message&&<p className="mt-6 text-xs text-black/45">{message}</p>}</aside>
  </div>
 </main>
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="block"><span className="mb-2 block text-[10px] uppercase tracking-[0.18em] text-black/35">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full border-b border-black/15 bg-transparent py-2 text-sm outline-none focus:border-black"/></label>}
