"use client";

import Link from "next/link";
import { ChangeEvent, DragEvent, useEffect, useMemo, useRef, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";
type Relic={id:string;file_path:string;title:string|null;author:string|null;source:string|null;url:string|null;notes:string|null;created_at:string};
const MAX_FILE_SIZE=10*1024*1024;
const STOP_WORDS=new Set(["a","al","algo","algun","alguna","algunas","alguno","algunos","ante","antes","aquel","aquella","aquellas","aquello","aquellos","aqui","asi","aun","aunque","bajo","bien","cada","casi","como","con","contra","cual","cuales","cuando","cuanto","cuantos","de","del","desde","donde","dos","durante","e","el","ella","ellas","ello","ellos","en","entre","era","eramos","eran","eras","eres","es","esa","esas","ese","eso","esos","esta","estaba","estaban","estado","estamos","estan","estar","estas","este","esto","estos","fue","fuera","fueron","ha","hace","hacia","han","hasta","hay","la","las","le","les","lo","los","mas","me","mi","mientras","mis","mismo","mucha","muchas","mucho","muchos","muy","nada","ni","no","nos","nuestra","nuestro","o","otra","otras","otro","otros","para","pero","poco","por","porque","que","quien","quienes","se","sea","segun","ser","si","sin","sobre","son","su","sus","tal","tambien","te","tener","tiene","tienen","todo","todos","tras","tu","tus","un","una","unas","uno","unos","usted","ustedes","ya","y","about","above","after","again","against","all","also","am","an","and","any","are","around","as","at","back","be","because","been","before","being","below","between","both","but","by","can","could","did","do","does","doing","down","during","each","few","for","from","further","had","has","have","having","he","her","here","hers","herself","him","himself","his","how","i","if","in","into","is","it","its","itself","just","me","more","most","my","myself","no","nor","not","now","of","off","on","once","only","or","other","our","ours","ourselves","out","over","own","same","she","should","so","some","such","than","that","the","their","theirs","them","themselves","then","there","these","they","this","those","through","to","too","under","until","up","very","was","we","were","what","when","where","which","while","who","whom","why","will","with","would","you","your","yours","yourself","yourselves","http","https","www","com","org","net"]);
const VERB_WORDS=new Set(["abri","abrio","abre","abren","abrir","cerrar","cerro","cierra","hago","hace","hacen","hacer","hizo","veo","ver","vemos","visto","parece","parecen","parecer","quiero","quiere","quieren","querer","gusta","gustan","gustar","interesa","interesan","interesar","funciona","funcionan","funcionar","utiliza","utilizan","utilizar","usa","usan","usar","crea","crean","crear","muestra","muestran","mostrar","genera","generan","generar","tiene","tienen","tener","puede","pueden","poder","debe","deben","deber","daria","diria","aim","aimed","aiming","looks","look","looking","seems","seem","using","uses","use","used","make","makes","making","made","show","shows","showing","create","creates","creating","created","feel","feels","feeling","like","likes","liked","want","wants","wanted","work","works","working","worked","give","gives","giving"]);
function normalizeWord(word:string){return word.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function canonicalWord(raw:string){let word=normalizeWord(raw);if(word.length>5&&word.endsWith("es"))word=word.slice(0,-2);else if(word.length>4&&word.endsWith("s"))word=word.slice(0,-1);return word}
function relicText(image:Relic){return[image.title,image.author,image.source,image.url,image.notes].filter(Boolean).join(" ")}
function relicWords(image:Relic){return relicText(image).match(/[\p{L}]+/gu)?.map(canonicalWord).filter(w=>w.length>=4&&!STOP_WORDS.has(w)&&!VERB_WORDS.has(w))??[]}
export default function Home(){
 const[session,setSession]=useState<Session|null>(null),[images,setImages]=useState<Relic[]>([]),[query,setQuery]=useState(""),[activeWord,setActiveWord]=useState(""),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[dragging,setDragging]=useState(false),[message,setMessage]=useState("");const[progress,setProgress]=useState({done:0,total:0});const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);useEffect(()=>{loadImages()},[]);
 async function loadImages(){setLoading(true);const{data,error}=await supabase.from("images").select("id,file_path,title,author,source,url,notes,created_at").order("created_at",{ascending:false});if(error)setMessage(error.message);else setImages(data??[]);setLoading(false)}
 async function uploadFiles(files:File[]){if(!session||uploading||!files.length)return;const imagesOnly=files.filter(f=>f.type.startsWith("image/"));const valid=imagesOnly.filter(f=>f.size<=MAX_FILE_SIZE);const tooLarge=imagesOnly.length-valid.length;if(!valid.length){setMessage(tooLarge?"No image was uploaded. Maximum size is 10 MB per image.":"No valid images selected.");return}setUploading(true);setProgress({done:0,total:valid.length});setMessage(tooLarge?`${tooLarge} image${tooLarge>1?"s were":" was"} skipped (maximum 10 MB).`:"");let failed=0;for(let i=0;i<valid.length;i++){const file=valid[i];const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${crypto.randomUUID()}.${ext}`;const{error:uploadError}=await supabase.storage.from("images").upload(path,file,{cacheControl:"3600",upsert:false});if(uploadError)failed++;else{const{error:insertError}=await supabase.from("images").insert({file_path:path});if(insertError){failed++;await supabase.storage.from("images").remove([path])}}setProgress({done:i+1,total:valid.length})}await loadImages();setUploading(false);setProgress({done:0,total:0});if(failed)setMessage(`${failed} image${failed>1?"s":""} could not be uploaded.`);else if(!tooLarge)setMessage("")}
 function handleFile(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files??[]);e.target.value="";void uploadFiles(files)}
 function handleDrop(e:DragEvent<HTMLElement>){e.preventDefault();setDragging(false);if(session)void uploadFiles(Array.from(e.dataTransfer.files))}
 const keywords=useMemo(()=>{const counts=new Map<string,number>();for(const image of images)for(const word of new Set(relicWords(image)))counts.set(word,(counts.get(word)??0)+1);return[...counts.entries()].filter(([,n])=>n>=2).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,30)},[images]);
 const filteredImages=useMemo(()=>{const search=normalizeWord(query.trim()),word=normalizeWord(activeWord);return images.filter(image=>(!search||normalizeWord(relicText(image)).includes(search))&&(!word||relicWords(image).includes(word)))},[images,query,activeWord]);
 function publicUrl(path:string){return supabase.storage.from("images").getPublicUrl(path).data.publicUrl}
 return <main onDragEnter={e=>{if(session){e.preventDefault();setDragging(true)}}} onDragOver={e=>{if(session)e.preventDefault()}} onDragLeave={e=>{if(e.currentTarget===e.target)setDragging(false)}} onDrop={handleDrop} className="min-h-screen bg-white text-black">
 <aside className="border-b border-black/10 bg-white px-4 py-4 md:fixed md:inset-y-0 md:left-0 md:z-20 md:w-52 md:overflow-y-auto md:border-b-0 md:border-r md:px-6 md:py-6"><nav><h1 className="mb-4 text-[26px] font-black leading-none md:mb-8">eye relics</h1><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search" className="mb-4 w-full border-b border-black/20 bg-transparent py-2 text-sm outline-none placeholder:text-black/35 focus:border-black md:mb-8"/><div className="flex items-center gap-4 overflow-x-auto pb-1 md:block md:overflow-visible"><button onClick={()=>setActiveWord("")} className={`shrink-0 text-xs font-medium uppercase tracking-widest md:mb-8 md:block ${activeWord?"opacity-35":""}`}>All</button><span className="shrink-0 text-[10px] uppercase tracking-[0.18em] text-black/35 md:mb-4 md:block">Words</span>{keywords.length===0?<p className="hidden text-xs text-black/30 md:block">No recurring words yet</p>:<div className="flex gap-3 md:block md:space-y-2">{keywords.map(([word,count])=><button key={word} onClick={()=>setActiveWord(activeWord===word?"":word)} className={`flex shrink-0 items-center gap-1.5 text-sm md:w-full md:justify-between ${activeWord===word?"font-medium":""}`}><span>{word}</span><span className="text-xs text-black/30">{count}</span></button>)}</div>}</div></nav></aside>
 <section className="min-h-screen p-2 md:ml-52 md:p-3">{message&&<p className="mb-3 px-2 text-xs text-black/50">{message}</p>}{loading?<p className="p-3 text-xs text-black/30">Loading...</p>:filteredImages.length===0?<div className="flex min-h-[60vh] items-center justify-center"><p className="text-xs text-black/30">{images.length===0?(session?"Use + or drop images here.":"No relics yet."):"No results."}</p></div>:<div className="columns-2 gap-2 md:columns-3 md:gap-3 lg:columns-4 xl:columns-5">{filteredImages.map(image=><Link key={image.id} href={`/relic/${image.id}`} className="mb-2 block break-inside-avoid overflow-hidden bg-zinc-100 transition-opacity hover:opacity-75 md:mb-3">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={publicUrl(image.file_path)} alt={image.title||"Eye Relic"} className="h-auto w-full" loading="lazy"/></Link>)}</div>}</section>
 {dragging&&session&&<div className="pointer-events-none fixed inset-3 z-50 flex items-center justify-center border border-dashed border-black/40 bg-white/90"><p className="text-xs uppercase tracking-[0.18em]">Drop images to add</p></div>}
 {uploading&&<div className="fixed bottom-20 right-5 z-40 bg-white px-3 py-2 text-xs shadow-sm ring-1 ring-black/10">Uploading {progress.done}/{progress.total}</div>}
 {session?<><input ref={fileInput} type="file" accept="image/*" multiple onChange={handleFile} className="hidden"/><button onClick={()=>fileInput.current?.click()} disabled={uploading} aria-label="Add images" className="fixed bottom-5 right-5 z-30 flex h-12 w-12 items-center justify-center rounded-full bg-black text-2xl font-light text-white shadow-sm disabled:opacity-25">{uploading?"·":"+"}</button></>:<a href="/login" className="fixed bottom-5 right-5 z-30 text-[10px] uppercase tracking-[0.18em] text-black/35">Login</a>}
 </main>
}
